# Site settings
title:          Xiaoxu
description:    "Home"
# baseurl:        "/tale"
url:            "https://xiaoxuchen.github.io"

# Google Analytics
# google_analytics: G-F3HF3GB75L

# Author
author:
  name:         Xiaoxu Chen
  url:          https://xiaoxuchen.github.io
  email:        xiaoxu.chen@mcgill.ca

# Build settings
markdown: kramdown
# kramdown:
#     math_engine: katex
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
paginate:       5
permalink:      /:year-:month-:day/:title
paginate_path: "/posts/page:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale